[build]
  command = "chmod +x ./build.sh && dash ./build.sh"
  functions = "functions"
  publish = "static"

[build.environment]
  GO_IMPORT_PATH = "github.com/DavidDengHui/depoly-go"
  GO111MODULE = "on"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/gateway/:splat"
  status = 200