[build]
  command = "chmod a+x build.sh && ./build.sh"
  functions = "functions"
  publish = "public"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./cmd ./public netlify.toml build.sh go.mod go.sum .go-version"

[build.environment]
  GO_IMPORT_PATH = "github.com/DavidDengHui/depoly-go"
  GO111MODULE = "on"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/gateway/:splat"
  status = 200

[[redirects]]
  from = "/get_api"
  to = "/.netlify/functions/gateway"
  status = 200

[[redirects]]
  from = "/get_web"
  to = "/.netlify/functions/gateway"
  status = 200

[[redirects]]
  from = "/get_img"
  to = "/.netlify/functions/gateway"
  status = 200

[[redirects]]
  from = "/readme"
  to = "/.netlify/functions/gateway"
  status = 200

[[redirects]]
  from = "/send_api"
  to = "/.netlify/functions/gateway"
  status = 200

[[redirects]]
  from = "/github"
  to = "/.netlify/functions/gateway"
  status = 200

[[redirects]]
  from = "/doit"
  to = "/.netlify/functions/gateway"
  status = 200
